### ISSUE TITLE
Can't download eclipse anymore, as download link has changed

### ISSUE THREAD

**Issue by 29axe** [ubuntu/ubuntu-make#325]
Hi,
I tried to install Eclipse using `umake ide eclipse` but this raises me an error : 

> ERROR: Download page changed its syntax or is not parsable

Same for eclipse-jee

I suppose eclipse changed their download urls.

**Comment by LyzardKing** [comment]
Yes. It just needed a small change in the url, just running the tests to be sure.

**Comment by LyzardKing** [comment]
fixed with #326

**Comment by 29axe** [comment]
Thanks for the quick reply. 
Working fine.

For people who also wants last version, here is how to get it.
From terminal: 
(_running Ubuntu 16.04_)
```
sudo apt-get update
sudo apt-get install git
sudo apt-get install python3-setuptools
git clone https://github.com/ubuntu/ubuntu-make.git
cd ubuntu-make/
sudo python3 setup.py build
sudo python3 setup.py install
```

**Comment by andresrivas1506** [comment]
```bash
$ sudo python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    import umake  # that initializes the gettext domain
  File "/home/andres/Code/proyectos/ubuntu/ubuntu-make/umake/__init__.py", line 28, in <module>
    from umake.frameworks import BaseCategory, load_frameworks
  File "/home/andres/Code/proyectos/ubuntu/ubuntu-make/umake/frameworks/__init__.py", line 33, in <module>
    from umake.network.requirements_handler import RequirementsHandler
  File "/home/andres/Code/proyectos/ubuntu/ubuntu-make/umake/network/requirements_handler.py", line 33, in <module>
    from umake.tools import Singleton, add_foreign_arch, get_foreign_archs, get_current_arch, as_root
  File "/home/andres/Code/proyectos/ubuntu/ubuntu-make/umake/tools.py", line 38, in <module>
    import yaml
ImportError: No module named 'yaml'
```

**Comment by 29axe** [comment]
You must install module yaml for python 3 apparently.

**Comment by LyzardKing** [comment]
Closing since it's no longer an issue
