### ISSUE TITLE
error when running in chroot created by customizer

### ISSUE THREAD

**Issue by MarkoSchuetz** [ubuntu/ubuntu-make#340]
I was customizing a live CD image for a programming competition using customizer. In the chroot I installed ubuntu-make to install a recent version of eclipse. I got this error:

Traceback (most recent call last):
  File "/usr/bin/umake", line 9, in <module>
    load_entry_point('Ubuntu-Make==16.2.1', 'console_scripts', 'umake')()
  File "/usr/lib/python3/dist-packages/umake/**init**.py", line 128, in main
    load_frameworks()
  File "/usr/lib/python3/dist-packages/umake/frameworks/**init**.py", line 365, in load_frameworks
    load_module(module_name, main_category)
  File "/usr/lib/python3/dist-packages/umake/frameworks/**init**.py", line 344, in load_module
    if FrameworkClass(current_category) is not None:
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 458, in **init**
    self._current_user = pwd.getpwuid(int(os.getenv("SUDO_UID", default=0))).pw_name
KeyError: 'getpwuid(): uid not found: 1000'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport/report.py", line 528, in add_proc_info
    self['ExecutablePath'] = os.readlink('/proc/' + pid + '/exe')
FileNotFoundError: [Errno 2] No such file or directory: '/proc/7855/exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 531, in add_proc_info
    raise ValueError('invalid process')
ValueError: invalid process

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/umake", line 9, in <module>
    load_entry_point('Ubuntu-Make==16.2.1', 'console_scripts', 'umake')()
  File "/usr/lib/python3/dist-packages/umake/**init**.py", line 128, in main
    load_frameworks()
  File "/usr/lib/python3/dist-packages/umake/frameworks/**init**.py", line 365, in load_frameworks
    load_module(module_name, main_category)
  File "/usr/lib/python3/dist-packages/umake/frameworks/**init**.py", line 344, in load_module
    if FrameworkClass(current_category) is not None:
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 458, in **init**
    self._current_user = pwd.getpwuid(int(os.getenv("SUDO_UID", default=0))).pw_name
KeyError: 'getpwuid(): uid not found: 1000'

**Comment by didrocks** [comment]
Hey! Sorry for the late answer.

I think the issue is that you don't have the same user mapping inside and outside your chroot.
So, SUDO_UID is 1000 (the user running the chroot), while internally in your chroot, you don't have any user with id 1000.

I guess you would need to create such an user in that chroot, would that work for you?

**Comment by didrocks** [comment]
Did you get any chance to try this?

**Comment by MarkoSchuetz** [comment]
Not yet. Might take some time before I'll get to it. Will post here...
