### ISSUE TITLE
impossible to install netbeans

### ISSUE THREAD

**Issue by boistordu** [ubuntu/ubuntu-make#364]
```
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 686, in parse_download_page_callback
    if not url_string:
UnboundLocalError: local variable 'url_string' referenced before assignment
```

version of umake from your apt (on 16.04)

**Comment by didrocks** [comment]
Thanks for reporting this bug!
This is supposed to be fixed in master, but not released yet (I'll release it in the next couple of weeks).
Do you mind trying from there?

```
git clone https://github.com/ubuntu/ubuntu-make
bin/umake <what you wanted to install>
```
and report the result here?

Thanks!

**Comment by boistordu** [comment]
okey i will try it

**Comment by boistordu** [comment]
bin/umake ide pycharm-professional /home/boistordu/pycharmpro
Downloading and installing requirements                                       |
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/home/vigilian/ubuntu-make/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/home/vigilian/ubuntu-make/umake/frameworks/baseinstaller.py", line 274, in get_progress
    if not self.pkg_to_install:
AttributeError: 'PyCharmProfessional' object has no attribute 'pkg_to_install'

**Comment by boistordu** [comment]
bin/umake ide netbeans /home/boistordu/netbeans[sudo] password for boistordu: 
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/home/boistordu/ubuntu-make/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/home/boistordu/ubuntu-make/umake/frameworks/ide.py", line 686, in parse_download_page_callback
    if not url_string:
UnboundLocalError: local variable 'url_string' referenced before assignment

**Comment by didrocks** [comment]
ok, thanks! something really regressed in the ide.py. @LyzardKing do you have time to look at this, maybe? ^

**Comment by LyzardKing** [comment]
Not for a while..I'll be away without a computer for the next 4-5 days

**Comment by LyzardKing** [comment]
The url slightly changed.
I'm running the tests to verify that nothing else is broken, but it'll be fixed soon
