### ISSUE TITLE
Golang: unexpected end of data

### ISSUE THREAD

**Issue by Schwobaland** [ubuntu/ubuntu-make#374]
The fallback from #362 isn't working on my system (Ubuntu 16.10). I cloned umake repository and called:

```
$ git clone https://github.com/ubuntu/ubuntu-make
$ ubuntu-make/bin/umake go
```
```
Installing Go Lang
ERROR: A decompression to /home/xxxx/.local/share/umake/go/go-lang failed: unexpected end of data                                                                       |
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 101, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.5/tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.5/tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib/python3.5/tarfile.py", line 243, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
ERROR: unexpected end of data

```

**Comment by didrocks** [comment]
Ah, not exactly! I think you discovered another bug :)
So, you are executing in that case the system version of ubuntu-make (`umake --version` would have confirmed that with the version number).
you need, to execute the local version, to:
```
$ git clone https://github.com/ubuntu/ubuntu-make
$ cd ubuntu-make
$ bin/umake go
```

**Comment by Schwobaland** [comment]
Thanks for your reply! I did exactly the same as you suggested. Only without `cd ubuntu-make`:

```
$ git clone https://github.com/ubuntu/ubuntu-make
$ ubuntu-make/bin/umake go
```

I think, I didn't call the system version of umake....

**Comment by didrocks** [comment]
did you try with the cd? That should be fixed.

You clearly otherwise called the system version of umake, as per:
```
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 101, in _decompress
    archive.extractall(tempdest)
```

which is the system version. Do the `cd` and you should be good :) (please file a bug about the fact that this cd shouldn't be needed)

**Comment by Schwobaland** [comment]
ok - you're right! Thanks for your help!
