### ISSUE TITLE
cd into project-directory needed to run umake

### ISSUE THREAD

**Issue by Schwobaland** [ubuntu/ubuntu-make#377]
After checking out ubuntu-make from github, an extra cd into the project-directory is needed to run umake. Otherwise the system version of umake is executed. See #374 for reference.

```
$ git clone https://github.com/ubuntu/ubuntu-make
$ ubuntu-make/bin/umake go
```
```
Installing Go Lang
ERROR: A decompression to /home/xxxx/.local/share/umake/go/go-lang failed: unexpected end of data                                                                       |
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/umake/decompressor.py", line 101, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.5/tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.5/tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.5/tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib/python3.5/tarfile.py", line 243, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
ERROR: unexpected end of data
```

Edit: Adding version:

```
# System version
~$ umake --version
16.05

# checked out version from parent directory
~/Dokumente/JUNK$ ubuntu-make/bin/umake --version
fatal: Not a git repository (or any of the parent directories): .git
16.09+unknown

# checked out version from project directory
~/Dokumente/JUNK/ubuntu-make$ bin/umake --version
16.09-28-gc977748

```

**Comment by didrocks** [comment]
perfect! Thanks a lot for opening that bug :)
