### ISSUE TITLE
html5lib problem

### ISSUE THREAD

**Issue by ipsod** [ubuntu/ubuntu-make#441]
I'm on Linux Mint 18 KDE, fully updated except for the kernel.

I installed ubuntu-make using:

    sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
    sudo apt-get update
    sudo apt-get install ubuntu-make

When I try to run `umake`, I got a stack trace:

    zero@mothership:~$ umake
    Traceback (most recent call last):
      File "/usr/bin/umake", line 9, in <module>
        load_entry_point('Ubuntu-Make==17.3', 'console_scripts', 'umake')()
      File "/usr/lib/python3/dist-packages/umake/__init__.py", line 128, in main
        load_frameworks()
      File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 365, in load_frameworks
        load_module(module_name, main_category)
      File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 332, in load_module
        import_module(module_abs_name)
      File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 24, in <module>
        from bs4 import BeautifulSoup
      File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
        from .builder import builder_registry, ParserRejectedMarkup
      File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
        from . import _html5lib
      File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
        class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
    AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

On stackoverflow, I found this comment (about beautifulsoup, not umake) - http://stackoverflow.com/a/41161317 - suggesting this fix - `pip install --upgrade html5lib==1.0b8` - which worked for me.

**Comment by didrocks** [comment]
Thanks for your bug report! and your detailed analysis.

Yeah, html5lib and beautifulsoup aren't matching the required version for Ubuntu Make on Linux Mint. Closing as we only support ubuntu releases and can't make it working both perfectly on ubuntu and mint which deviates in this regard. You can install at the html5lib/beautifulsoup from pip, but that might conflicts with other packages on your system.

You might open a bug on the Linux Mint bug tracking tool so that they align their html5lib/beautifulsoup version swith ubuntu one.
