### ISSUE TITLE
Umake Not Running on Ubuntu 16.04 after using pip

### ISSUE THREAD

**Issue by sahil48** [ubuntu/ubuntu-make#445]
I'm getting an error running the umake command from the terminal in Ubuntu 16.04. The error message is below. I have ubuntu-make 17.03 installed, python 2.7.12, and python 3.5.2 installed. I'm not sure what the issue is, and any suggestions for troubleshooting this issue would be much appreciated.

~~~~~~~~~~~~
Traceback (most recent call last):
  File "/usr/bin/umake", line 9, in <module>
    load_entry_point('Ubuntu-Make==17.3', 'console_scripts', 'umake')()
  File "/usr/lib/python3/dist-packages/umake/__init__.py", line 128, in main
    load_frameworks()
  File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 365, in load_frameworks
    load_module(module_name, main_category)
  File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 332, in load_module
    import_module(module_abs_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 24, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
~~~~~~~~~~~~~~~

**Comment by LyzardKing** [comment]
Hi!
In the title you said you used pip. What did you do exactly?
Did you install a different version of something that umake depends on?
(A different version of html5lib?)

**Comment by sahil48** [comment]
I used pip to install jupyter notebook (https://jupyter.org/install.html). It's possible it affected the version of html5lib. Synaptic says that the version I have installed in 0.999-4.

**Comment by LyzardKing** [comment]
check what version pip says you have installed: pip3 show html5lib

**Comment by LyzardKing** [comment]
If that returns a version other than the one that you had in synaptic, then that's the issue.
I would recommend to install jupyter notebook in a virtualenv(https://docs.python.org/3/library/venv.html) if possible, so you don't change libraries the system relies on.

**Comment by sahil48** [comment]
It is different (Version: 0.999999999). Thank you very much for your quick feedback. Could you also suggest how I revert my system's python installation/environment, or at least html5lib back to how it was?

**Comment by LyzardKing** [comment]
Actually, that might be the right version. In pip3 show html5lib you should see where it's installed.
If it's in /usr/lib/python3/dist-packages it's the correct package. if it's in something like site-packages then you need to remove the pip version with pip3 uninstall html5lib

**Comment by sahil48** [comment]
Thanks. This worked and umake is working. The command I had to use, for reference is:

`sudo -H pip3 uninstall html5lib`.

Thanks for all your help. I really appreciate it. I am closing this issue now that it is resolved.

**Comment by LyzardKing** [comment]
Great!
