### ISSUE TITLE
Does umake support arm64 architecture?

### ISSUE THREAD

**Issue by bstassel** [Ubuntu/ubuntu-make#532]
Here is what happens after I install umake. It seems the games.py file only has "amd64" and "i386" as available architectures.

```
system@user:~$ umake --help
Traceback (most recent call last):
  File "/usr/bin/umake", line 9, in <module>
    load_entry_point('Ubuntu-Make==17.3', 'console_scripts', 'umake')()
  File "/usr/lib/python3/dist-packages/umake/__init__.py", line 142, in main
    load_frameworks(force_loading=should_load_all_frameworks(sys.argv))
  File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 420, in load_frameworks
    load_module(module_name, main_category, force_loading)
  File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 335, in load_module
    import_module(module_abs_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/umake/frameworks/games.py", line 97, in <module>
    class Blender(umake.frameworks.baseinstaller.BaseInstaller):
  File "/usr/lib/python3/dist-packages/umake/frameworks/games.py", line 112, in Blender
    arch = arch_trans[get_current_arch()]
KeyError: 'arm64'
```

**Comment by LyzardKing** [comment]
Hi! What are you trying to install?
Umake could install even arm binaries, since it's not tied to a single architecture.
If it has arm64 binaries, and you could test it (since I don't have the proper hardware) we can add it!

**Comment by bstassel** [comment]
I specifically was trying to install the eclipse-cpp ide: "umake ide eclipse-cpp". I thought eclipse was able to run on arm64 architecture, but I could be wrong. 

For some background, I have a Jetson TX2 development kit (arm64) and am trying use it with a ZED camera system for an autonomous navigation system on a rover for my club.

Thanks!

**Comment by LyzardKing** [comment]
I don't think it's available for other architectures...
https://www.eclipse.org/downloads/packages/eclipse-ide-cc-developers/heliossr2
If there's another repo let me know

**Comment by LyzardKing** [comment]
Closing for now since eclipse has no arm packages (At least not in the main website...)
If this changes we should revisit this.
