### ISSUE TITLE
umake snap installation fails

### ISSUE THREAD

**Issue by Suncatcher** [ubuntu/ubuntu-make#536]
I ran installation according to manual

    snap install ubuntu-make --classic

but `ubuntu-make.umake` throws this

    Traceback (most recent call last):
      File "/snap/ubuntu-make/225/bin/umake", line 11, in <module>
        load_entry_point('Ubuntu-Make==17.3', 'console_scripts', 'umake')()
      File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
        return ep.load()
      File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/snap/ubuntu-make/225/lib/python3.5/site-packages/umake/__init__.py", line 30, in <module>
        from .ui import cli
      File "/snap/ubuntu-make/225/lib/python3.5/site-packages/umake/ui/cli/__init__.py", line 28, in <module>
        import readline
    ImportError: libreadline.so.6: cannot open shared object file: No such file or directory

system: Xubuntu 17.10
de: xfce4

**Comment by LyzardKing** [comment]
The snap wasn't working properly.
I'm testing a few different setups.
What distro are you running?

**Comment by Suncatcher** [comment]
> system: Ubuntu 17.10
> de: xfce4

**Comment by LyzardKing** [comment]
Try and refresh the snap(possibly edge). But I'm not sure it's working now

**Comment by Suncatcher** [comment]
> refresh the snap

if under this you mean `snap refresh` then no, that didn't help.

**Comment by LyzardKing** [comment]
What about snap refresh ubuntu-make --edge?

**Comment by Suncatcher** [comment]
Yep, that worked.
However, when I try to install eclipse throught umake it throws:

    atata@tratata:~$ ubuntu-make.umake ide eclipse
    Traceback (most recent call last):
      File "/snap/ubuntu-make/229/bin/umake", line 6, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 972, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 858, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'Ubuntu-Make==17.3' distribution was not found and is required by the application

Probably this should be separate issue. Is it a lower umake version than eclipse expects? Or opposite higher? I can't even check umake version:

    atata@tratata:~$ ubuntu-make.umake --version
    Traceback (most recent call last):
      File "/snap/ubuntu-make/229/bin/umake", line 11, in <module>
        load_entry_point('Ubuntu-Make==17.3', 'console_scripts', 'umake')()
      File "/snap/ubuntu-make/229/lib/python3.5/site-packages/umake/__init__.py", line 145, in main
        cli.main(parser)
      File "/snap/ubuntu-make/229/lib/python3.5/site-packages/umake/ui/cli/__init__.py", line 243, in main
        print(get_version())
      File "/snap/ubuntu-make/229/lib/python3.5/site-packages/umake/settings.py", line 37, in get_version
        version = open(os.path.join(os.path.dirname(__file__), 'version'), 'r', encoding='utf-8').read().strip()
    FileNotFoundError: [Errno 2] No such file or directory: '/snap/ubuntu-make/229/lib/python3.5/site-packages/umake/version'

**Comment by LyzardKing** [comment]
I need to look at the snap more...
I'm trying a few changes to get it to work.
For now the suggestion is to install the ppa

**Comment by Suncatcher** [comment]
Thanks, ppa worked.

**Comment by LyzardKing** [comment]
The snap should work now. If you can test it let me know!
Closing for now.

**Comment by o-MoSes** [comment]
Hey,

i got the same Problem on Ubuntu 16.04 (4.13.0-38-generic)

```
ubuntu-make.umake ide eclipse
Traceback (most recent call last):
  File "/snap/ubuntu-make/225/bin/umake", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Ubuntu-Make==17.3' distribution was not found and is required by the application
```

**Comment by LyzardKing** [comment]
@o-MoSes could you try this and see if it works?
run `snap run --shell ubuntu-make.umake`
then at the prompt type these two commands, to set the correct environment:
```
export PYTHONUSERBASE=$SNAP
export PYTHONHOME=$SNAP/usr
```
then (from the same terminal prompt) try and run `ubuntu-make.umake ide eclipse` again and see if it works

**Comment by o-MoSes** [comment]
Yup, didnt work. 

> Choose installation path: /home/o-moses/.local/share/umake/ide/eclipse
Downloading and installing requirements                                                                  |
100% |###################################################################################################|
Installing Eclipse
ERROR: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/snap/ubuntu-make/225/lib/python3.5/site-packages/umake/version'
|########################################################################################################|
Installation done
<

Can i delete everything starting from .../ide ?

I will use the ppa for now. Thanx!

**Comment by LyzardKing** [comment]
You can install the umake ppa, then if you run umake ice eclipse it'll
replace everything. You don't need to remove anything.
Thanks for testing the snap...I'm still trying to figure it out
