### ISSUE TITLE
ImportError: libreadline.so.6 on Ubuntu 18.04

### ISSUE THREAD

**Issue by fertkir** [ubuntu/ubuntu-make#542]
I'm on Ubuntu 18.04.
Installed ubuntu-make via `snap install ubuntu-make --classic`
When running `ubuntu-make.umake --list` I get the following output:
```
Traceback (most recent call last):
  File "/snap/ubuntu-make/225/bin/umake", line 11, in <module>
    load_entry_point('Ubuntu-Make==17.3', 'console_scripts', 'umake')()
  File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/snap/ubuntu-make/225/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/snap/ubuntu-make/225/lib/python3.5/site-packages/umake/__init__.py", line 30, in <module>
    from .ui import cli
  File "/snap/ubuntu-make/225/lib/python3.5/site-packages/umake/ui/cli/__init__.py", line 28, in <module>
    import readline
ImportError: libreadline.so.6: cannot open shared object file: No such file or directory
```

**Comment by LyzardKing** [comment]
I'm aware of this issue.
I'll push a version with a fix to the snap, but it might only work on pre 18.04..
There's an issue open at: https://forum.snapcraft.io/t/ld-library-path-in-classic-snap/5030
For 18.04 atm your best bet is to install the ppa (you can find the details in the README)

**Comment by fertkir** [comment]
Okey, thank you.
