### ISSUE TITLE
umake installed rust failed

### ISSUE THREAD

**Issue by netroby** [ubuntu/ubuntu-make#588]
```
huzhifeng@yoshi ~/.local $ umake rust
Choose installation path: /home/huzhifeng/.local/share/umake/rust/rust-lang

Downloading and installing requirements                                                                                |
100% |#################################################################################################################|
Installing Rust Lang
ERROR: Unhandled exception                                                                                          #  |
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 458, in decompress_and_install_done
    self.post_install()
  File "/usr/lib/python3/dist-packages/umake/frameworks/rust.py", line 78, in post_install
    os.path.join(self.install_path, 'rustc', 'lib', 'rustlib', arch_lib_folder, 'lib'))
FileExistsError: [Errno 17] 文件已存在: '/home/huzhifeng/.local/share/umake/rust/rust-lang/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib' -> '/home/huzhifeng/.local/share/umake/rust/rust-lang/rustc/lib/rustlib/x86_64-unknown-linux-gnu/lib'
|######################################################################################################################|

```

**Comment by LyzardKing** [comment]
This should now be fixed in https://github.com/ubuntu/ubuntu-make/commit/b3161c8ea322cff0d1f78a4596708766529fe0fc
Let me know if it works since I've had to change the symlink magic..
