### ISSUE TITLE
ERROR: One default was already registered, can't register a second one in that choices set

### ISSUE THREAD

**Issue by Jamesking56** [ubuntu/ubuntu-make#592]
umake version 18.09 installed on Ubuntu 18.04 LTS via ppa.

When I run `umake web firefox-dev` I get this error:

```
ERROR: One default was already registered, can't register a second one in that choices set: ['en-US', 'en-US', 'ach', 'af', 'sq', 'ar', 'an', 'hy-AM', 'as', 'ast', 'az', 'eu', 'be', 'bn-BD', 'bn-IN', 'bs', 'br', 'bg', 'my', 'ca', 'zh-CN', 'zh-TW', 'hr', 'cs', 'da', 'nl', 'en-GB', 'en-CA', 'en-ZA', 'en-US', 'eo', 'et', 'fi', 'fr', 'fy-NL', 'ff', 'gd', 'gl', 'ka', 'de', 'el', 'gn', 'gu-IN', 'he', 'hi-IN', 'hu', 'is', 'id', 'ia', 'ga-IE', 'it', 'ja', 'kab', 'kn', 'cak', 'kk', 'km', 'ko', 'lv', 'lij', 'lt', 'dsb', 'mk', 'mai', 'ms', 'ml', 'mr', 'ne-NP', 'nb-NO', 'nn-NO', 'oc', 'or', 'fa', 'pl', 'pt-BR', 'pt-PT', 'pa-IN', 'ro', 'rm', 'ru', 'sr', 'si', 'sk', 'sl', 'son', 'es-AR', 'es-CL', 'es-MX', 'es-ES', 'sv-SE', 'ta', 'te', 'th', 'tr', 'uk', 'hsb', 'ur', 'uz', 'vi', 'cy', 'xh']
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/web.py", line 116, in get_metadata_and_check_license
    UI.delayed_display(TextWithChoices(_("Choose language: {}".format(default_label)), languages, True))
  File "/usr/lib/python3/dist-packages/umake/interactions/__init__.py", line 59, in __init__
    raise BaseException(message)
BaseException: One default was already registered, can't register a second one in that choices set: ['en-US', 'en-US', 'ach', 'af', 'sq', 'ar', 'an', 'hy-AM', 'as', 'ast', 'az', 'eu', 'be', 'bn-BD', 'bn-IN', 'bs', 'br', 'bg', 'my', 'ca', 'zh-CN', 'zh-TW', 'hr', 'cs', 'da', 'nl', 'en-GB', 'en-CA', 'en-ZA', 'en-US', 'eo', 'et', 'fi', 'fr', 'fy-NL', 'ff', 'gd', 'gl', 'ka', 'de', 'el', 'gn', 'gu-IN', 'he', 'hi-IN', 'hu', 'is', 'id', 'ia', 'ga-IE', 'it', 'ja', 'kab', 'kn', 'cak', 'kk', 'km', 'ko', 'lv', 'lij', 'lt', 'dsb', 'mk', 'mai', 'ms', 'ml', 'mr', 'ne-NP', 'nb-NO', 'nn-NO', 'oc', 'or', 'fa', 'pl', 'pt-BR', 'pt-PT', 'pa-IN', 'ro', 'rm', 'ru', 'sr', 'si', 'sk', 'sl', 'son', 'es-AR', 'es-CL', 'es-MX', 'es-ES', 'sv-SE', 'ta', 'te', 'th', 'tr', 'uk', 'hsb', 'ur', 'uz', 'vi', 'cy', 'xh']
```

**Comment by LyzardKing** [comment]
Hi. Thanks for the issue!
It's fixed now, and will be up in a while.
For now if you want you can just run `umake web firefox --lang en-US` (replacing en-US with the lang you want). That still works

**Comment by LyzardKing** [comment]
Closed by https://github.com/ubuntu/ubuntu-make/commit/cf2c9a4f38f03baf62f9d68d09e42d39c3a1f3de

**Comment by EndermanAPM** [comment]
> Hi. Thanks for the issue!
> It's fixed now, and will be up in a while.
> For now if you want you can just run `umake web firefox --lang en-US` (replacing en-US with the lang you want). That still works

Note that you need to use `firefox-dev` to install firefox developer version.
