### ISSUE TITLE
Dart SDK installation fails with NoneType object returned to request

### ISSUE THREAD

**Issue by point-source** [ubuntu/ubuntu-make#603]
**OS**: PopOS 19.04 & Ubuntu 19.04 (tested both separately)
**umake version**: 19.04 installed from PPA & master branch from this repo (tested both separately)

Attempting to install the dart-sdk results in this error:
```
root@9fd90f62f2ba:/ubuntu-make# bin/umake dart dart-sdk
Choose installation path: /root/.local/share/umake/dart/dart-sdk
ERROR: None couldn't finish download: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/ubuntu-make/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/ubuntu-make/umake/frameworks/dart.py", line 86, in get_sha_and_start_download
    checksum = res.buffer.getvalue().decode('utf-8').split()[0]
AttributeError: 'NoneType' object has no attribute 'getvalue'
```

**Comment by LyzardKing** [comment]
This should be fixed now.
The webpage changed, so we needed to change the parsing ;)
thanks for pointing this out!
