### ISSUE TITLE
ERROR: Protocol not supported. when trying to download Eclipse

### ISSUE THREAD

**Issue by Boza-s6** [ubuntu/ubuntu-make#69]
```
Choose installation path: /home/nxx/tools/ide/eclipse
ERROR: https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5&r=1 couldn't finish download: Protocol not supported.
ERROR: Protocol not supported.
CRITICAL: Exception in worker
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/network/download_center.py", line 120, in _fetch
    with closing(requests.get(url, stream=True, headers=headers)) as r:
  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 585, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 585, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 179, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 608, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'ftp://ftp.gtlib.gatech.edu/pub/eclipse/technology/epp/downloads/release/luna/R/eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz.md5'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/umake/network/download_center.py", line 134, in _fetch
    raise BaseException("Protocol not supported.") from exc
BaseException: Protocol not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 65, in _worker
    work_item.run()
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 56, in run
    self.future.set_exception(e)
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 504, in set_exception
    self._invoke_callbacks()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3/dist-packages/umake/network/download_center.py", line 182, in _one_done
    self._done()
  File "/usr/lib/python3/dist-packages/umake/network/download_center.py", line 190, in _done
    self._done_callback(self._downloaded_content)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 83, in done
    UI.return_main_screen()
  File "/usr/lib/python3/dist-packages/umake/ui/__init__.py", line 35, in return_main_screen
    cls.currentUI._return_main_screen(status_code=status_code)
  File "/usr/lib/python3/dist-packages/umake/ui/cli/__init__.py", line 53, in _return_main_screen
    MainLoop().quit(status_code=status_code)
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 138, in quit
    raise self.ReturnMainLoop()
umake.tools.ReturnMainLoop
```

**Comment by Tinche** [comment]
Acknowledged.

Ugh, looks like Eclipse is redirecting to FTP. Will take a look tonight.

**Comment by didrocks** [comment]
/me feels an emergency release tomorrow :)
Thanks Tin for looking at this and thanks Boza for the bug report!

**Comment by Tinche** [comment]
Ok, so I spent the evening getting a medium test case to fail by redirecting to FTP. (Added Twisted to our Docker image to serve as an easy-to-use FTP server, hope it's OK). Now (well, tomorrow) I need to actually make the test fail.

I thought about using https://github.com/Lukasa/requests-ftp for this, but I don't think it supports stream=True. We'll probably need to special-case the exception in download center and handle it manually using Python's ftplib.

**Comment by didrocks** [comment]
@Tin: thanks for looking at this! Yeah, no worry as long as you add things to the docker images and not a runtime dep. So twisted is fine for this.

Ack on the download center, keep me posted!

**Comment by Tinche** [comment]
This should be fixed by #70. @Boza-s6, please retest when you get the new release (depending on whether you're running it from git or PPA).

**Comment by Boza-s6** [comment]
I installed it from PPA, so I have to wait for update before I test.

**Comment by didrocks** [comment]
We'll probably cut a release tomorrow, so stay tuned! :)

**Comment by didrocks** [comment]
Done in 0.5 (http://blog.didrocks.fr/post/Ubuntu-Make-0.5-adds-four-new-platforms)! Please keep us posted :)
