### ISSUE TITLE
Blender download URL broken

### ISSUE THREAD

**Issue by rocha** [ubuntu/ubuntu-make#692]
```
❯ umake --version
22.10+snap976

❯  umake games blender
Choose installation path: /home/rocha/.local/share/umake/games/blender
Downloading and installing requirements                                                                                                                            |
ERROR: https://download.blender.org/release/release/Blender3.6/blender-3.6.4-linux-x64.tar.xz couldn't finish download: 404 Client Error: Not Found for url: https://download.blender.org/release/release/Blender3.6/blender-3.6.4-linux-x64.tar.xz
100% |#############################################################################################################################################################|
ERROR: 404 Client Error: Not Found for url: https://download.blender.org/release/release/Blender3.6/blender-3.6.4-linux-x64.tar.xz
```

**Comment by LyzardKing** [comment]
Hi @rocha 
Thanks for the notification.
It should work with the updated version. It'll take a while to rebuild, but you should receive the update soon enough.

Let me know if it starts working again!

**Comment by rocha** [comment]
Hi @LyzardKing, thanks for checking. I am getting a different error now. Seems like it is downloading an invalid file (maybe trying to untar a html file?)

```
❯ umake --version
22.10+snap1010
~ took 5s
❯ umake games blender
Choose installation path: /home/rocha/.local/share/umake/games/blender
Downloading and installing requirements                                                                                                                                                                                   |
100% |####################################################################################################################################################################################################################|
Installing Blender
ERROR: A decompression to /home/rocha/.local/share/umake/games/blender failed: [Errno 8] Exec format error: '/tmp/tmp7_nwmvem.xz.safe'                                                                                    |
Traceback (most recent call last):
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 187, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'e>\n\t\t<me'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 2318, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 1105, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 1047, in frombuf
    chksum = nti(buf[148:156])
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 189, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/ubuntu-make/1010/lib/python3.8/site-packages/umake/decompressor.py", line 98, in _decompress
    archive = tarfile.open(fileobj=fd, mode='r|*')
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 1633, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 1514, in __init__
    self.firstmember = self.next()
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/tarfile.py", line 2330, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/ubuntu-make/1010/lib/python3.8/site-packages/umake/decompressor.py", line 101, in _decompress
    archive = self.ZipFileWithPerm(fd.name)
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/ubuntu-make/1010/lib/python3.8/site-packages/umake/decompressor.py", line 127, in _decompress
    archive = subprocess.Popen([name, "-o{}".format(tempdest)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/ubuntu-make/1010/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/tmp/tmp7_nwmvem.xz.safe'
ERROR: [Errno 8] Exec format error: '/tmp/tmp7_nwmvem.xz.safe'
|#########################################################################################################################################################################################################################|
```

**Comment by LyzardKing** [comment]
@rocha It should work now in master.
